name: chatconnect_mobile
description: "ChatConnect Pro - Cross-platform mobile chat app with webhook integration"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Networking
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3

  # Local Storage
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  # Audio
  audioplayers: ^6.0.0
  just_audio: ^0.9.38
  audio_session: ^0.1.19

  # Speech-to-Text
  speech_to_text: ^7.3.0
  permission_handler: ^11.3.1

  # UI/UX
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  shimmer: ^3.0.0

  # Utilities
  uuid: ^4.4.0
  intl: ^0.20.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  crypto: ^3.0.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1

  # Deep Linking
  uni_links: ^0.5.1

  # Local Auth
  local_auth: ^2.2.0

  # Logging
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  json_serializable: ^6.8.0
  freezed: ^2.5.2

  # Testing
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
